baseURL = "https://mikejobrien.com/"
languageCode = "en-us"
title = "Mike J. O'Brien"
copyright = "This is a customized copyright."
disableKinds = ["section"]
theme = "diary"
googleAnalytics = "UA-89523532-1"

[params]
subtitle = "My Personal site."
enableGitalk = false

#[params.gitalk]
#  owner = "obrienmikej"
#  repo = "mikejobrien.com"
#  client_id = "your client id"
#  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"
