baseurl = "http://mikejobrien.com.s3-website-us-west-1.amazonaws.com/"
languageCode = "en-us"
title = "Mike J. O'Brien's blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "mjo"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "UA-89523532-1"
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
# themesDir = "../.."

[params]
    site_author = "Mike J. O'Brien"
    site_description = "Mike J. O'Brien's blog."
    location = "Walnut Creek, CA"
    # Link custom assets relative to /static
    avatar = "img/mike_obrien_150.jpg"
    header_background = "img/lights.jpg"
    header_title = "Motocross Racer & Enthusiast"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-89523532-1"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "obrienmikej"
    facebook  = "obrienmikej"
    linkedin  = "obrienmikej"
    behance   = ""
    dribbble  = ""
    instagram = "obrienmikej"
    github    = "obrienmikej"
    gplus     = ""
