[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links
[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/obrienmikej"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/obrienmikej"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/obrienmikej/"
