#build my site and deploy to deploy to S3

name: Build and Deploy Hugo Site

# Controls when the action will run. Triggers the workflow on push
# events but only for the main branch
on:
  push:
    branches: [main]

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.3.0

      # Sets up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: "0.119.0"
          extended: true

      # Builds mikejobrien.com repo
      - name: Build
        run: hugo --minify

      # Deploys built website to S3
      - name: Deploy to S3
        run: hugo deploy --force --maxDeletes -1 --invalidateCDN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
